# Generated by Django 4.2.6 on 2023-10-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
